### ISSUE TITLE
[Errno 2] No such file or directory: u'/Users/XXX/Desktop/TndrLocalizer-master/output/XXX_XXXX.kml'

### ISSUE THREAD

**Issue by halalfood** [Vinz87/TndrLocalizer#1]
[Errno 2] No such file or directory: u'/Users/XXX/Desktop/TndrLocalizer-master/output/XXX_XXXX.kml'

Everything works up to this line: kmlObject[i].save(parent_folder + "output/" + name_list[i] + "_" + id[-4:] + ".kml")

It's not saving to a document because it can't find one. It checks if there is a document, then skips over it if there isn't one.

**Comment by Vinz87** [comment]
did you create an "output" folder?

**Comment by halalfood** [comment]
working now. had to remove "parent folder" part
